### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by yrkFukushima** [yrkFukushima/git-app#4]
#URL
https://furima-35594.herokuapp.com/

#Basic認証のIDとパスワード
 ID admin 
 Password 3333

#出品者用のメールアドレスとパスワード
 mail hanako@test
 password 123asd

#購入者用のメールアドレスとパスワード
 mail reiko@test
 password  123asd

**Comment by takumi0530** [comment]
@yrkFukushima さん、お待たせいたしました。ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

### **[修正依頼箇所]**

- [ ] **商品名やカテゴリーの情報など、すでに登録されている商品情報は商品情報編集画面を開いた時点で表示されること**
添付画像の部分の情報が表示されていませんでした。
<img width="558" alt="スクリーンショット 2021-05-13 10 53 47" src="https://user-images.githubusercontent.com/76197191/118066456-ba4fd000-b3d9-11eb-97ba-8ee1bb632d50.png">

- [ ] **ログイン状態のユーザーが、URLを直接入力して売却済み商品の商品購入ページへ遷移しようとすると、トップページに遷移すること**
購入ページに遷移できてしまいました。


修正が完了しましたら、再度以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by takumi0530** [comment]
@yrkFukushima さん、 再度ご提出ありがとうございます‼︎
動作の確認をしたところ、一部の修正が確認できませんでした。
マージやデプロイ忘れの可能性もありますので、改めてご確認をお願いします！

### **[修正依頼箇所]**

- [ ] **商品名やカテゴリーの情報など、すでに登録されている商品情報は商品情報編集画面を開いた時点で表示されること**
<img width="603" alt="スクリーンショット 2021-05-13 12 28 41" src="https://user-images.githubusercontent.com/76197191/118073499-e7ef4600-b3e6-11eb-9be4-964787b2b87d.png">


修正が完了しましたら、再度以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by yrkFukushima** [comment]
ありがとうございます。商品名やカテゴリーの情報など、すでに登録されている商品情報は商品情報編集画面を開いた時点で表示されること。に関しまして、
商品名やカテゴリーの情報など、すでに登録されている商品情報は商品情報編集画面を開いた時点で表示されること（商品画像・販売手数料・販売利益に関しては、表示されない状態で良い）
と要件定義されております。

ご確認いただけますと幸いです。

**Comment by takumi0530** [comment]
@yrkFukushima さん、ご質問ありがとうございます！

**商品名やカテゴリーの情報など、すでに登録されている商品情報は商品情報編集画面を開いた時点で表示されること（商品画像・販売手数料・販売利益に関しては、表示されない状態で良い）**

こちらの定義に関しまして、**表示されなくて良い部分**は、

**①商品画像**
<img width="598" alt="スクリーンショット 2021-05-13 12 38 27" src="https://user-images.githubusercontent.com/76197191/118074023-22a5ae00-b3e8-11eb-8c78-a73efc5d9b3b.png">

**②販売手数料・販売利益**
<img width="624" alt="スクリーンショット 2021-05-13 12 38 56" src="https://user-images.githubusercontent.com/76197191/118074071-32bd8d80-b3e8-11eb-96c7-f9217ac424b6.png">

こちらの部分になりますので、今回ご依頼させていただいた、「配送について」部分の表示は必要となります。
また何かご不明点がございましたらお気軽にご質問いただければと思います。よろしくお願い致します。

修正が完了しましたら、再度以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by takumi0530** [comment]
@yrkFukushima さん、ご提出ありがとうございます‼︎
問題なく正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉
着実に技術力が身につき、実用的なアプリになってきてますね（^^）
これからもスタッフ一同応援しております🍀

**※確認したのは必須機能のみです。追加実装した機能については確認しておりません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるか、再度ご自身でご確認をお願い致します。**
![最終課題終了_おめでとう画像2](https://user-images.githubusercontent.com/76197191/118080128-87ff9c00-b3f4-11eb-8626-722327df4184.png)

**Comment by yrkFukushima** [comment]
> #URL
> https://furima-35594.herokuapp.com/
> 
> #Basic認証のIDとパスワード
> ID admin
> Password 3333
> 
> #出品者用のメールアドレスとパスワード
> mail hanako@test
> password 123asd
> 
> #購入者用のメールアドレスとパスワード
> mail reiko@test
> password 123asd
